// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOCt687bHgV0vJSY4QYM3D-PtBAAWm6Q4',
    appId: '1:778239383653:web:0ebd81c62dfa1149434e8c',
    messagingSenderId: '778239383653',
    projectId: 'food-recipe-1c48a',
    authDomain: 'food-recipe-1c48a.firebaseapp.com',
    storageBucket: 'food-recipe-1c48a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClUL81x5HszRxcOADgJmgjbn25wKYg_VQ',
    appId: '1:778239383653:android:7bc74a3fcbe158b2434e8c',
    messagingSenderId: '778239383653',
    projectId: 'food-recipe-1c48a',
    storageBucket: 'food-recipe-1c48a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAGZ85yGVvFpnrwLR-w5vdn2pNHMe88kA',
    appId: '1:778239383653:ios:86e6113f66a24b65434e8c',
    messagingSenderId: '778239383653',
    projectId: 'food-recipe-1c48a',
    storageBucket: 'food-recipe-1c48a.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAGZ85yGVvFpnrwLR-w5vdn2pNHMe88kA',
    appId: '1:778239383653:ios:86e6113f66a24b65434e8c',
    messagingSenderId: '778239383653',
    projectId: 'food-recipe-1c48a',
    storageBucket: 'food-recipe-1c48a.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOCt687bHgV0vJSY4QYM3D-PtBAAWm6Q4',
    appId: '1:778239383653:web:bc4760602233ab7a434e8c',
    messagingSenderId: '778239383653',
    projectId: 'food-recipe-1c48a',
    authDomain: 'food-recipe-1c48a.firebaseapp.com',
    storageBucket: 'food-recipe-1c48a.appspot.com',
  );
}
